/**
 * @filename HHTouchEventHandler.h
 * @author Morgan Wall
 * @date 29-9-2013
 *
 * @brief A protocol to be implemented on any node classes that are to be included
 * as descendants to a state node in the state stack describing the game. This 
 * protocol is used to handle events generated by the user by distributing it 
 * throughout the nodes in the scene graph (in post order traversal) until it
 * as been handled or there are no nodes remaining.
 */

#import <Foundation/Foundation.h>

@protocol HHEventHandler <NSObject>

/**
 * @brief Handle an event generated by the user.
 *
 * @param event
 * The event generated by the user.
 *
 * @param touch
 * Information about the touch event generated by the user.
 *
 * @returns true if the event was completely handled by the node, otherwise false.
 */
- (BOOL)handleEvent:(UIEvent*)event touch:(UITouch*)touch;

@end
