/**
 * @filename SSKActionHandler.h
 * @author Morgan Wall
 * @date 28-9-2013
 *
 * @brief A protocol to be implemented on any node classes that are to be included
 * as descendants to a state node in the state stack describing the game. This
 * protocol is used to handle actions generated by the game by distributing it
 * throughout the nodes in the scene graph (in post order traversal) until it
 * as been handled or there are no nodes remaining.
 */

#import <Foundation/Foundation.h>
#import <SpriteStackKit/SSKAction.h>

@protocol SSKActionHandler <NSObject>

@required

/**
 * @brief Handle an action generated by the game.
 *
 * @param action
 * The action to be handled.
 */
- (void)onAction:(SSKAction*)action;

/**
 * @brief Retrieve the action category of the node.
 *
 * @returns the action category of the node.
 */
- (unsigned int)getActionCategory;

@end
